version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - /root/keycloak/volume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_FRONTEND_URL: https://keycloak.datnxdevops.site/auth
      KC_HTTPS_REQUIRED: all
      KC_HOSTNAME: https://keycloak.datnxdevops.site
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: true
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    command: ["start-dev"] 
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
